id: https://w3id.org/sssom/walker_config
name: walker-confic
description: Schema for Walker Config
imports:
- linkml:types
prefixes:
  linkml: https://w3id.org/linkml/
  config: https://w3id.org/sssom/walker_config/
default_prefix: config

enums:
  EndpointEnum:
    permissible_values:
      OxO:
      BioPortal:
types:
  MaximumCount:
    typeof: integer
    #minimum_value: 0
  Directory:
    typeof: string
  FilePath:
    typeof: string
classes:
  BoomerConfiguration:
    description: >-
      A configuration for boomer command line options
    attributes:
      runs:
        range: MaximumCount
      window:
        range: MaximumCount
  EndpointConfiguration:
    description: >-
      A configuration for a mapping endpoint
    attributes:
      type:
        range: EndpointEnum
  PipelineConfiguration:
    description: >-
      A configuration for a pipeline
    attributes:
      endpoint_configurations:
        range: EndpointConfiguration
        multivalued: true
        inlined: true
        inlined_as_list: true
      max_clique_size:
        description: >-
          Limit to size of clique to build when iteratively querying endpoints
        range: MaximumCount
      max_hops:
        description: >-
          Maximum distance from seed nodes when iteratively querying endpoints
        range: MaximumCount
      working_directory:
        description: >-
          folder in which to store working files
        range: Directory
      stylesheet:
        description: >-
          path to an obographviz json stylesheet
        range: FilePath
      boomer_configuration:
        range: BoomerConfiguration
